#!/usr/bin/env bash
set -euo pipefail

# --- Configuration ---
WORKTREE_ROOT=$(git rev-parse --show-toplevel)
GIT_COMMON_DIR=$(git rev-parse --git-common-dir)
REGISTRY="${GIT_COMMON_DIR}/port-registry.json"
LOCK_DIR="${GIT_COMMON_DIR}/.port-registry.lock"
BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")

# --- Prerequisite check ---
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required. Install with: brew install jq" >&2
  exit 1
fi

# --- Initialize registry if missing ---
init_registry() {
  if [ ! -f "$REGISTRY" ]; then
    cat > "$REGISTRY" << 'JSON'
{
  "version": 1,
  "step": 100,
  "max_slots": 10,
  "base_ports": {
    "API_PORT": 33001,
    "WEB_PORT": 33000,
    "POSTGRES_PORT": 35432,
    "REDIS_PORT": 36379,
    "NATS_PORT": 34222,
    "NATS_MGMT_PORT": 38222,
    "CENTRIFUGO_PORT": 38000
  },
  "slots": {}
}
JSON
  fi
}

# --- File locking (mkdir-based, portable) ---
acquire_lock() {
  local attempts=0
  while ! mkdir "$LOCK_DIR" 2>/dev/null; do
    attempts=$((attempts + 1))
    if [ $attempts -gt 50 ]; then
      echo "ERROR: Could not acquire registry lock after 5s" >&2
      exit 1
    fi
    sleep 0.1
  done
  trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT
}

# --- Garbage-collect stale slots ---
gc_stale_slots() {
  local content
  content=$(cat "$REGISTRY")
  local changed=false

  for slot in $(echo "$content" | jq -r '.slots | keys[]'); do
    local wt
    wt=$(echo "$content" | jq -r ".slots[\"$slot\"].worktree")
    if [ ! -d "$wt" ]; then
      content=$(echo "$content" | jq "del(.slots[\"$slot\"])")
      changed=true
      echo "GC: released stale slot ${slot} (${wt})"
    fi
  done

  if [ "$changed" = true ]; then
    echo "$content" > "${REGISTRY}.tmp"
    mv "${REGISTRY}.tmp" "$REGISTRY"
  fi
}

# --- Check if this worktree already has a slot ---
check_existing_slot() {
  jq -r --arg wt "$WORKTREE_ROOT" \
    '.slots | to_entries[] | select(.value.worktree == $wt) | .key' \
    "$REGISTRY" | head -1
}

# --- Find lowest available slot ---
find_available_slot() {
  local max_slots
  max_slots=$(jq -r '.max_slots // 10' "$REGISTRY")

  for i in $(seq 0 $((max_slots - 1))); do
    if ! jq -e ".slots[\"$i\"]" "$REGISTRY" >/dev/null 2>&1; then
      echo "$i"
      return 0
    fi
  done

  echo "ERROR: All ${max_slots} port slots occupied." >&2
  echo "Run: scripts/port-registry-gc.sh" >&2
  return 1
}

# --- Claim a slot ---
claim_slot() {
  local slot=$1
  local ts
  ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  jq --arg slot "$slot" \
     --arg wt "$WORKTREE_ROOT" \
     --arg branch "$BRANCH" \
     --arg ts "$ts" \
     '.slots[$slot] = {worktree: $wt, branch: $branch, allocated_at: $ts}' \
     "$REGISTRY" > "${REGISTRY}.tmp"
  mv "${REGISTRY}.tmp" "$REGISTRY"
}

# --- Generate .env ---
generate_env() {
  local slot=$1
  local step
  step=$(jq -r '.step // 100' "$REGISTRY")
  local offset=$((slot * step))

  # Read base ports from registry (single source of truth)
  local api_port=$(($(jq -r '.base_ports.API_PORT' "$REGISTRY") + offset))
  local web_port=$(($(jq -r '.base_ports.WEB_PORT' "$REGISTRY") + offset))
  local pg_port=$(($(jq -r '.base_ports.POSTGRES_PORT' "$REGISTRY") + offset))
  local redis_port=$(($(jq -r '.base_ports.REDIS_PORT' "$REGISTRY") + offset))
  local nats_port=$(($(jq -r '.base_ports.NATS_PORT' "$REGISTRY") + offset))
  local nats_mgmt_port=$(($(jq -r '.base_ports.NATS_MGMT_PORT' "$REGISTRY") + offset))
  local centrifugo_port=$(($(jq -r '.base_ports.CENTRIFUGO_PORT' "$REGISTRY") + offset))

  # Local dev credential defaults (not real secrets — used only for local Docker containers)
  local db_user="${CTRLPANE_DB_USER:-ctrlpane_app}"
  local db_password="${CTRLPANE_DB_PASSWORD:-ctrlpane_dev}"
  local redis_password="${CTRLPANE_REDIS_PASSWORD:-ctrlpane_dev}"
  local centrifugo_api_key="${CTRLPANE_CENTRIFUGO_API_KEY:-ctrlpane_dev_api_key}"
  local centrifugo_hmac="${CTRLPANE_CENTRIFUGO_HMAC_SECRET:-ctrlpane_dev_hmac_secret}"

  cat > "${WORKTREE_ROOT}/.env" << ENV
# Auto-generated by worktree-enter.sh — slot ${slot}
# DO NOT EDIT — managed by port registry

# Database
DATABASE_URL=postgres://${db_user}:${db_password}@localhost:${pg_port}/ctrlpane
POSTGRES_PORT=${pg_port}
POSTGRES_PASSWORD=${db_password}

# Redis
REDIS_URL=redis://:${redis_password}@localhost:${redis_port}
REDIS_PORT=${redis_port}
REDIS_PASSWORD=${redis_password}

# NATS
NATS_URL=nats://localhost:${nats_port}
NATS_PORT=${nats_port}
NATS_MGMT_PORT=${nats_mgmt_port}

# Centrifugo
CENTRIFUGO_URL=http://localhost:${centrifugo_port}
CENTRIFUGO_PORT=${centrifugo_port}
CENTRIFUGO_API_KEY=${centrifugo_api_key}
CENTRIFUGO_HMAC_SECRET=${centrifugo_hmac}

# API
API_PORT=${api_port}
API_HOST=127.0.0.1

# Web
WEB_PORT=${web_port}

# Docker Compose
COMPOSE_PROJECT_SUFFIX=slot-${slot}

# Environment
NODE_ENV=development
LOG_LEVEL=debug
ENV
}

# --- Generate .worktree-info ---
generate_worktree_info() {
  local slot=$1
  local step
  step=$(jq -r '.step // 100' "$REGISTRY")
  local offset=$((slot * step))

  local api_port=$(($(jq -r '.base_ports.API_PORT' "$REGISTRY") + offset))
  local web_port=$(($(jq -r '.base_ports.WEB_PORT' "$REGISTRY") + offset))

  cat > "${WORKTREE_ROOT}/.worktree-info" << INFO
# Worktree: ${BRANCH} (slot ${slot})
# Web:  http://localhost:${web_port}
# API:  http://localhost:${api_port}/health/live
INFO
}

# --- Main ---
main() {
  acquire_lock
  init_registry
  gc_stale_slots

  local slot
  slot=$(check_existing_slot)

  if [ -n "$slot" ]; then
    echo "Worktree already allocated to slot ${slot}"
  else
    slot=$(find_available_slot) || exit 1
    claim_slot "$slot"
  fi

  generate_env "$slot"
  generate_worktree_info "$slot"

  echo "=== Port Allocation ==="
  echo "Slot:   ${slot}"
  echo "Branch: ${BRANCH}"
  cat "${WORKTREE_ROOT}/.worktree-info"
  echo "======================="
}

main
